name: Find code
jobs:
  crawl:
    name: Crawl Github for code
    runs-on: ubuntu-latest
    steps:
      - name: Crawl
      - run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $(cat /Volumes/Encrypted/2024-11-11-github-token-codecrawler)" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        "https://api.github.com/search/code?q=language:hcl"
  
      
