name: Find code
on:
  workflow_dispatch:
jobs:
  crawl:
    name: Crawl Github for code
    runs-on: ubuntu-latest
    steps:
      - name: Crawl
        run: |
          curl -q -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/search/code?q=language:hcl" >response
  
          cat response | jq '.items[] | .git_url' | while read URL; do
           curl -q $URL
          done
          
